[config]
schemaVersion = "0.0.1"

[package]
namespace = "CheatMenu"
name = "CheatMenu"
versionNumber = "1.2.90"
description = "CheatMenu"
websiteUrl = "https://github.com/asd9176506911298/NineSolsPlugin"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.4.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
